name: Azure Resource deployment

variables:
  - template: variables.yaml

parameters:
  - name: stages
    displayName: "Various Stage to execute in pipeline."
    type: object
    default: 
      - rg
      - adls
      - kv
      - adf
  
  - name: deploymentType
    displayName: "Type of deployment"
    type: string
    default: bulkDeployment
  
  - name: bu
    displayName: "Name of business unit"
    type: string
    default: bcmp

  - name: action
    displayName: "Action to perform. Default value is build. Allowed values of build and destroy"
    type: string
    default: build
    values:
    - build
    - destroy

resources:
 repositories:
   - repository: cambansal0588             // change it
     name: cambansal0588/cambansal0588     // change it
     ref: '$(Build.SourceBranch)'
     type: git
     trigger:
      branches:
        include:
          - master
          - releases/*
      paths:
        include:
          - devsecops/*


stages:
- ${{ each stage in parameters.stages }}:
  - ${{ if eq(parameters.action, 'build') }}:
    - stage: '${{ stage }}_build'
      jobs:
      - template: ../template/pipeline.build.yaml
        parameters:
          mdname: '${{ stage }}'
          moduleName: '${{ stage }}'
          workingDirectory: '$(Agent.BuildDirectory)/repo/tfcode/${{ stage }}'
          dependsOn: ''
          condition: ''
          deploymentFolder: 'deployment'
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
            backendServiceArm: '${{ variables.pp_backendServiceArm }}'
            backendAzureRmResourceGroupName: '${{ variables.pp_backendAzureRmResourceGroupName }}'
            backendAzureRmStorageAccountName: '${{ variables.pp_backendAzureRmStorageAccountName }}'
            backendAzureRmContainerName: '${{ variables.pp_backendAzureRmContainerName }}'
            backendAzureRmKey: '${{ parameters.deploymentType }}-${{ parameters.bu }}-${{ stage }}-pp.tfstate'
            keyvault: '${{ variables.pp_keyvault }}'
            env: '${{ variables.pp_env }}'
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/features') }}:
            backendServiceArm: ${{ variables.de_backendServiceArm }}
            backendAzureRmResourceGroupName: ${{ variables.de_backendAzureRmResourceGroupName }}
            backendAzureRmStorageAccountName: ${{ variables.de_backendAzureRmStorageAccountName }}
            backendAzureRmContainerName: ${{ variables.de_backendAzureRmContainerName }}
            backendAzureRmKey: ${{ parameters.deploymentType }}-${{ parameters.bu }}-${{ stage }}-de.tfstate
            keyvault: ${{ variables.de_keyvault }}
            env: ${{ variables.de_env }}
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/releases') }}:
            backendServiceArm: ${{ variables.pr_backendServiceArm }}
            backendAzureRmResourceGroupName: ${{ variables.pr_backendAzureRmResourceGroupName }}
            backendAzureRmStorageAccountName: ${{ variables.pr_backendAzureRmStorageAccountName }}
            backendAzureRmContainerName: ${{ variables.pr_backendAzureRmContainerName }}
            backendAzureRmKey: '${{ parameters.deploymentType }}-${{ parameters.bu }}-${{ stage }}-pr.tfstate'
            keyvault: ${{ variables.pr_keyvault }}
            env: ${{ variables.pr_env }}
  
    - stage : ${{ stage }}_deploy
      dependsOn: ${{ stage }}_build
      jobs:
      - template: ../template/pipeline.deploy.yaml
        parameters:
          mdname: '${{ stage }}'
          moduleName: '${{ stage }}'
          workingDirectory: '$(Agent.BuildDirectory)/repo/tfcode/${{ stage }}'
          dependsOn: ''
          condition: ''
          deploymentFolder: 'deployment'
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
            backendServiceArm: '${{ variables.pp_backendServiceArm }}'
            backendAzureRmResourceGroupName: '${{ variables.pp_backendAzureRmResourceGroupName }}'
            backendAzureRmStorageAccountName: '${{ variables.pp_backendAzureRmStorageAccountName }}'
            backendAzureRmContainerName: '${{ variables.pp_backendAzureRmContainerName }}'
            backendAzureRmKey: '${{ parameters.deploymentType }}-${{ parameters.bu }}-${{ stage }}-pp.tfstate'
            keyvault: '${{ variables.pp_keyvault }}'
            env: '${{ variables.pp_env }}'
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/features') }}:
            backendServiceArm: ${{ variables.de_backendServiceArm }}
            backendAzureRmResourceGroupName: ${{ variables.de_backendAzureRmResourceGroupName }}
            backendAzureRmStorageAccountName: ${{ variables.de_backendAzureRmStorageAccountName }}
            backendAzureRmContainerName: ${{ variables.de_backendAzureRmContainerName }}
            backendAzureRmKey: ${{ parameters.deploymentType }}-${{ parameters.bu }}-${{ stage }}-de.tfstate
            keyvault: ${{ variables.de_keyvault }}
            env: ${{ variables.de_env }}
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/releases') }}:
            backendServiceArm: ${{ variables.pr_backendServiceArm }}
            backendAzureRmResourceGroupName: ${{ variables.pr_backendAzureRmResourceGroupName }}
            backendAzureRmStorageAccountName: ${{ variables.pr_backendAzureRmStorageAccountName }}
            backendAzureRmContainerName: ${{ variables.pr_backendAzureRmContainerName }}
            backendAzureRmKey: '${{ parameters.deploymentType }}-${{ parameters.bu }}-${{ stage }}-pr.tfstate'
            keyvault: ${{ variables.pr_keyvault }}
            env: ${{ variables.pr_env }}